
---
title: "faceted_taxa_boxplots"
author: "Aleah Wong"
date: '2024-09-24'
output: html_document
---

```{r}
rm(list = ls())
.rs.restartR()

library(ggplot2)
library(dplyr)
library(tidyr)

library(tidyverse)
library(ggpubr)
library(rstatix)
```

###TEST
```{r}

cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#D55E00", "#CC79A7")

cbPalette1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

wongpalette <- c("#DC267F", "#785EF0", "#648FFF", "#FE6100", "#FFB000")

tolpalette <- c("#332288", "#117733", "#40B0A6", "#88CCEE", "#E1BE6A", "#CC6677", "#AA4499", "#882255")


tolpalettesub <- c("#DC267F", "#785EF0", "#648FFF")



# "#40B0A6","#E1BE6A","#332288"

```


###F
```{r Graphing means}

setwd("/Users/aleahw/Documents/Master's!!/Chapter_2/Figures")

scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Fscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column

#modify dataset: create three time periods
# scores_3_periods <- merge

scores_3_periods$Year[scores_3_periods$Year >= 1950 & scores_3_periods$Year <= 1980] <- "I"
scores_3_periods$Year[scores_3_periods$Year >= 1981 & scores_3_periods$Year <= 2000] <- "II"
scores_3_periods$Year[scores_3_periods$Year >= 2001 & scores_3_periods$Year <= 2021] <- "III"

Food <- ggplot(scores_3_periods, aes(x = Year, y=Score, color = weighted_by))+ geom_boxplot()+
  stat_summary(fun.y=mean,geom='point', position = position_dodge(width = .75))+
  # stat_summary(fun=mean, geom="line", aes(group=weighted_by), position = position_dodge(width = .75))+
  scale_y_continuous(limits = c(30, 67))+
      # scale_x_continuous(breaks = c(1963, 1990, 2010), labels = c("Early expansion", "Intensification", "Recent Growth"))+
      geom_vline(xintercept = 1.5, linetype = "dashed")+ #vertical lines
      geom_vline(xintercept = 2.5, linetype = "dashed")+
      geom_vline(xintercept = 3.5, linetype = "dashed")+
        labs(y = "", x = "Pf")+
        # labs(y = "Mean Index", x = "Year")+
          theme_classic()+
          theme(axis.text.x = element_text(size = 10), axis.title.x = element_text(size = 15), axis.text.y = element_text(size = 15), legend.title = element_text(size=15), legend.text = element_text(size = 15))+
            scale_color_manual(name = "Weighted By", breaks = c("Algae", "Crustaceans", "Finfish", "Molluscs", "All"), values= cbPalette)
    

# ggsave("mean_F_boxplots.png", Food, height = 4, width = 8, dpi = 600) #make sure wd is set
```

#Paired sample t-tests
##test that distributions are equal
```{r}
#Normality tests

#ALL, F
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Fscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "All")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p > 0.05; Normally distributed

# QQ plot for the difference
ggqqplot(wide3, "differences")

#looks normal!
-------------------------------------
#Algae, F
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Fscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Algae")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p < 0.05; Not normally distributed

# QQ plot for the difference
ggqqplot(wide3, "differences") 

# #Use wilcoxon test
# wide3 <- wide3[, -c(1, 3, 5)]
# wide3 <- pivot_longer(wide3, cols = c("before", "after"), names_to = "group", values_to = "score")
# 
# before <- subset(wide3,  group == "before", score,
#                  drop = TRUE)
# # subset weight data after treatment
# after <- subset(wide3,  group == "after", score,
#                  drop = TRUE)
# 
# res <- wilcox.test(before, after, paired = TRUE)
# res
-------------------------------------
#Crustaceans, F
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Fscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Crustaceans")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p > 0.05; NOT significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")
-------------------------------------
#Finfish, F
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Fscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Finfish")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p > 0.05; NOT significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")

-------------------------------------
#Molluscs, F
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Fscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Molluscs")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p < 0.05; IS significantly different from normal distribution

# QQ plot for the difference
ggqqplot(wide3, "differences")

#Use wilcoxon test for molluscs
# #Use wilcoxon test
# wide3 <- wide3[, -c(1, 3, 5)]
# wide3 <- pivot_longer(wide3, cols = c("before", "after"), names_to = "group", values_to = "score")
# 
# before <- subset(wide3,  group == "before", score,
#                  drop = TRUE)
# # subset weight data after treatment
# after <- subset(wide3,  group == "after", score,
#                  drop = TRUE)
# 
# res <- wilcox.test(before, after, paired = TRUE)
# res
```

#Conducting the t-tests
```{r}
#look at the difference between means for "all taxonomic groups" between period 2 and 3

#remove period 1 from scores_3_periods, only "all"
data <- subset(scores_3_periods, weighted_by == "All")
data <- subset(data, Year == "II" | Year == "III")

--------------------
#FOOD
res_f <- t.test(Score ~ Year, data = data)
p_f <- res_f$p.value
print(p_f)
#p = 5.144273e-15

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#mean in period two: 53.6, SD = 0.34
#mean in period three: 52.3, SD = 0.361

###################for the taxonomic groups:
#ALGAE--use wilcoxon test, non-normal distribution
# data <- subset(scores_3_periods, weighted_by == "Algae")
# data <- subset(data, Year == "II" | Year == "III")

# data %>%
#   group_by(Year) %>%
#   get_summary_stats(Score, type = "mean_sd")

#CRUSTACEANS
data <- subset(scores_3_periods, weighted_by == "Crustaceans")
data <- subset(data, Year == "II" | Year == "III")

res_f <- t.test(Score ~ Year, data = data)
p_f <- res_f$p.value
print(p_f)
#p = 

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#FINFISH
data <- subset(scores_3_periods, weighted_by == "Finfish")
data <- subset(data, Year == "II" | Year == "III")

res_f <- t.test(Score ~ Year, data = data)
p_f <- res_f$p.value
print(p_f)
#p = 

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#MOLLUSCS--use wilcoxon
data <- subset(scores_3_periods, weighted_by == "Molluscs")
data <- subset(data, Year == "II" | Year == "III")

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")
```

###C
```{r Graphing means in three time periods}

#modify dataset: create three time periods
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Cscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column

scores_3_periods$Year[scores_3_periods$Year >= 1950 & scores_3_periods$Year <= 1980] <- "I"
scores_3_periods$Year[scores_3_periods$Year >= 1981 & scores_3_periods$Year <= 2000] <- "II"
scores_3_periods$Year[scores_3_periods$Year >= 2001 & scores_3_periods$Year <= 2021] <- "III"


Climate <-ggplot(scores_3_periods, aes(x = Year, y=Score, color = weighted_by))+ geom_boxplot()+
  stat_summary(fun.y=mean,geom='point', position = position_dodge(width = .75))+
  # stat_summary(fun=mean, geom="line", aes(group=weighted_by), position = position_dodge(width = .75))+
  scale_y_continuous(limits = c(30, 67))+
      # scale_x_continuous(breaks = c(1963, 1990, 2010), labels = c("Early expansion", "Intensification", "Recent Growth"))+
      geom_vline(xintercept = 1.5, linetype = "dashed")+ #vertical lines
      geom_vline(xintercept = 2.5, linetype = "dashed")+
      geom_vline(xintercept = 3.5, linetype = "dashed")+
        labs(y = "", x = "Pc")+
        # labs(y = "Mean Index", x = "Year")+
          theme_classic()+
          theme(axis.text.x = element_text(size = 10), axis.title.x = element_text(size = 15), axis.text.y = element_text(size = 15), legend.title = element_text(size=15), legend.text = element_text(size = 15))+
            scale_color_manual(name = "Weighted By", breaks = c("Algae", "Crustaceans", "Finfish", "Molluscs", "All"), values= cbPalette)

# setwd("/Users/aleahw/Documents/Master's!!/Chapter_2/Figures")
# ggsave("mean_C_boxplots.png", Climate, height = 4, width = 8, dpi = 600) #make sure wd is set
```

```{r}
#Normality tests

#ALL, C
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Cscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "All")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p > 0.05; not significantly different from normal distribution

# QQ plot for the difference
ggqqplot(wide3, "differences")
-------------------------------------
#Algae, C
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Cscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Algae")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p < 0.05; IS significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences") 

# #Use wilcoxon test
# wide3 <- wide3[, -c(1, 3, 5)]
# wide3 <- pivot_longer(wide3, cols = c("before", "after"), names_to = "group", values_to = "score")
# 
# before <- subset(wide3,  group == "before", score,
#                  drop = TRUE)
# # subset weight data after treatment
# after <- subset(wide3,  group == "after", score,
#                  drop = TRUE)
# 
# res <- wilcox.test(before, after, paired = TRUE)
# res
-------------------------------------
#Crustaceans, C
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Cscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Crustaceans")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p >0.05; NOT significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")
-------------------------------------
#Finfish, C
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Cscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Finfish")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p < 0.05; IS significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")

# #Use wilcoxon test
# wide3 <- wide3[, -c(1, 3, 5)]
# wide3 <- pivot_longer(wide3, cols = c("before", "after"), names_to = "group", values_to = "score")
# 
# before <- subset(wide3,  group == "before", score,
#                  drop = TRUE)
# # subset weight data after treatment
# after <- subset(wide3,  group == "after", score,
#                  drop = TRUE)
# 
# res <- wilcox.test(before, after, paired = TRUE)
# res
-------------------------------------
#Molluscs, C
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Cscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Molluscs")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p < 0.05; IS significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")

#Use wilcoxon test for molluscs
#Use wilcoxon test
# wide3 <- wide3[, -c(1, 3, 5)]
# wide3 <- pivot_longer(wide3, cols = c("before", "after"), names_to = "group", values_to = "score")
# 
# before <- subset(wide3,  group == "before", score,
#                  drop = TRUE)
# # subset weight data after treatment
# after <- subset(wide3,  group == "after", score,
#                  drop = TRUE)
# 
# res <- wilcox.test(before, after, paired = TRUE)
# res
```

#Paired sample t-tests
```{r}
#look at the difference between means for "all taxonomic groups" between period 2 and 3

#remove period 1 from scores_3_periods, only "all"
data <- subset(scores_3_periods, weighted_by == "All")
data <- subset(data, Year == "II" | Year == "III")

#CLIMATE
res_c <- t.test(Score ~ Year, data = data)
p_c <- res_c$p.value
print(p_c)
#p = 1.336511e-13

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#mean in period two: 53.7, SD = 0.671
#mean in period three: 51.3, SD = 0.69

###################for the taxonomic groups:
#ALGAE
data <- subset(scores_3_periods, weighted_by == "Algae")
data <- subset(data, Year == "II" | Year == "III")

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#CRUSTACEANS
data <- subset(scores_3_periods, weighted_by == "Crustaceans")
data <- subset(data, Year == "II" | Year == "III")

res_c <- t.test(Score ~ Year, data = data)
p_c <- res_c$p.value
print(p_c)

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#FINFISH
data <- subset(scores_3_periods, weighted_by == "Finfish")
data <- subset(data, Year == "II" | Year == "III")

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#MOLLUSCS
data <- subset(scores_3_periods, weighted_by == "Molluscs")
data <- subset(data, Year == "II" | Year == "III")

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")
```

###B
```{r Graphing means in three time periods}
#magnitude of F, C and B indices by taxonomic group in three time periods

#modify dataset: create three time periods
# scores_3_periods <- merge
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Bscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column

scores_3_periods$Year[scores_3_periods$Year >= 1950 & scores_3_periods$Year <= 1980] <- "I"
scores_3_periods$Year[scores_3_periods$Year >= 1981 & scores_3_periods$Year <= 2000] <- "II"
scores_3_periods$Year[scores_3_periods$Year >= 2001 & scores_3_periods$Year <= 2021] <- "III"

Biodiv <-ggplot(scores_3_periods, aes(x = Year, y=Score, color = weighted_by))+ geom_boxplot()+
  stat_summary(fun.y=mean,geom='point', position = position_dodge(width = .75))+
  # stat_summary(fun=mean, geom="line", aes(group=weighted_by), position = position_dodge(width = .75))+
  scale_y_continuous(limits = c(30, 67))+
      geom_vline(xintercept = 1.5, linetype = "dashed")+ #vertical lines
      geom_vline(xintercept = 2.5, linetype = "dashed")+
      geom_vline(xintercept = 3.5, linetype = "dashed")+
        labs(y = "", x = "Pb")+
        # labs(y = "Mean Index", x = "Year")+
          theme_classic()+
          theme(axis.text.x = element_text(size = 10), axis.title.x = element_text(size = 15), axis.text.y = element_text(size = 15), legend.title = element_text(size=15), legend.text = element_text(size = 15))+
            scale_color_manual(name = "Weighted By", breaks = c("Algae", "Crustaceans", "Finfish", "Molluscs", "All"), values= cbPalette)

# setwd("/Users/aleahw/Documents/Master's!!/Chapter_2/Figures")
# ggsave("mean_B_boxplots.png", Biodiv, height = 4, width = 8, dpi = 600) #make sure wd is set
```

```{r}
#Normality tests

#ALL, B
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Bscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "All")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p > 0.05; not significantly different from normal distribution

# QQ plot for the difference
ggqqplot(wide3, "differences")
-------------------------------------
#Algae, B
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Bscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Algae")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p > 0.05; NOT significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences") 
-------------------------------------
#Crustaceans, B
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Bscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Crustaceans")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p < 0.05; IS significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")

# #Use wilcoxon test
# wide3 <- wide3[, -c(1, 3, 5)]
# wide3 <- pivot_longer(wide3, cols = c("before", "after"), names_to = "group", values_to = "score")
# 
# before <- subset(wide3,  group == "before", score,
#                  drop = TRUE)
# # subset weight data after treatment
# after <- subset(wide3,  group == "after", score,
#                  drop = TRUE)
# 
# res <- wilcox.test(before, after, paired = TRUE)
# res
-------------------------------------
#Finfish, B
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Bscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Finfish")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p > 0.05; NOT significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")
-------------------------------------
#Molluscs, B
scores_3_periods <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/weighted_Bscores.csv")
scores_3_periods <- scores_3_periods[, c(2:4)] #remove extra column
subset <- subset(scores_3_periods, weighted_by == "Molluscs")

wide1 <- subset[c(31:51), c(1, 2)]
wide2 <- subset[c(52:72),c(1, 2)]
library(dplyr)
wide3 <- cbind(wide1, wide2)
colnames(wide3)[1] <- "Period 2"
colnames(wide3)[2] <- "before"
colnames(wide3)[3] <- "Period 3"
colnames(wide3)[4] <- "after"

wide3 <- wide3 %>% mutate(differences = before - after)

#identify outliers
wide3 %>% identify_outliers(differences) #There were no extreme outliers.

#Check normality assumption:
# Shapiro-Wilk normality test for the differences
wide3 %>% shapiro_test(differences) #p < 0.05; IS significantly different from normal

# QQ plot for the difference
ggqqplot(wide3, "differences")

#Use wilcoxon test for molluscs
#Use wilcoxon test
# wide3 <- wide3[, -c(1, 3, 5)]
# wide3 <- pivot_longer(wide3, cols = c("before", "after"), names_to = "group", values_to = "score")
# 
# before <- subset(wide3,  group == "before", score,
#                  drop = TRUE)
# # subset weight data after treatment
# after <- subset(wide3,  group == "after", score,
#                  drop = TRUE)
# 
# res <- wilcox.test(before, after, paired = TRUE)
# res
```

#Paired sample t-tests
```{r}
#look at the difference between means for "all taxonomic groups" between period 2 and 3

#remove period 1 from scores_3_periods, only "all"
data <- subset(scores_3_periods, weighted_by == "All")
data <- subset(data, Year == "II" | Year == "III")

#CLIMATE
res_b <- t.test(Score ~ Year, data = data)
p_b <- res_b$p.value
print(p_b)
#p = 0.006088108

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#mean in period two: 56.6, SD = 1.34
#mean in period three: 55.6, SD = 0.586

###################for the taxonomic groups:
#ALGAE
data <- subset(scores_3_periods, weighted_by == "Algae")
data <- subset(data, Year == "II" | Year == "III")

res_b <- t.test(Score ~ Year, data = data)
p_b <- res_b$p.value
print(p_b)

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#CRUSTACEANS
data <- subset(scores_3_periods, weighted_by == "Crustaceans")
data <- subset(data, Year == "II" | Year == "III")

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#FINFISH
data <- subset(scores_3_periods, weighted_by == "Finfish")
data <- subset(data, Year == "II" | Year == "III")

res_b <- t.test(Score ~ Year, data = data)
p_b <- res_b$p.value
print(p_b)

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")

#MOLLUSCS
data <- subset(scores_3_periods, weighted_by == "Molluscs")
data <- subset(data, Year == "II" | Year == "III")

data %>%
  group_by(Year) %>%
  get_summary_stats(Score, type = "mean_sd")
```

```{r COMBINED FCB GRAPH WEIGHTED BY PRODUCTION OF ALL SPECIES}

#load in the data saved in steps 5-7
F_weighted_all <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Fweightedby_all.csv")
F_weighted_all <- F_weighted_all[, c(2:3)]
C_weighted_all <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Cweightedby_all.csv")
C_weighted_all <- C_weighted_all[, c(2:3)]
B_weighted_all <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Bweightedby_all.csv")
B_weighted_all <- B_weighted_all[, c(2:3)]

#Add FCB labels to each dataset before merging
F_weighted_all$Index <- "Food Security"
#weighted_indexesc = C weighted by all 
C_weighted_all$Index <- "Climate Change"
#weighted_indexesb = B weighted by all 
B_weighted_all$Index <- "Biodiversity"

#put into one dataframe, all stacked up
merge <- rbind(F_weighted_all, C_weighted_all)
merge <- rbind(merge, B_weighted_all)

#graph
together <-
  ggplot(merge, aes(x=Year, y=Score, color = Index)) +geom_line(size =1)+
  labs(y = "Mean Index", x = "")+ #title = "FCB Potential of Aquaculture Weighted by 54 Major Species"
    # theme(axis.text.x = element_text(size = 10), axis.title.y = element_text(size=10))+
  theme_classic()+
  theme(axis.text.x = element_text(size = 15), axis.title.x = element_text(size = 15), axis.ticks.x=element_blank(), axis.text.y = element_text(size = 15), axis.title.y = element_text(size = 20), legend.title = element_text(size=15), legend.text = element_text(size = 15))+
      scale_color_manual(name = "Index", values=tolpalettesub)+
      scale_y_continuous(breaks = c(48, 50, 52, 54, 56, 58, 60))+
      scale_x_continuous(breaks = c(1950, 1963, 1980, 1990, 2000, 2010, 2021), labels = c("1950", "I", "1980", "II", "2000", "III", "2021"))+
        geom_vline(xintercept = 1980, linetype = "dashed")+ #vertical lines
        geom_vline(xintercept = 2000, linetype = "dashed")+
        geom_vline(xintercept = 2021, linetype = "dashed")
  # ylim(48, 60)
  # angle = 15, vjust = 0.8, hjust = 0.6


#SAVE
setwd("/Users/aleahw/Documents/Master's!!/Chapter_2/Figures")
# ggsave("FCB_weightedby_all.png", together, height = 4, width = 8, dpi = 600) #make sure wd is set
```

```{r}
library(patchwork)
 # & xlab(NULL)

#Fig a) Climate
#Fig b) Biodiv
# Fig c) Food

# fig <- (together | Food) / (Biodiv | Climate) & theme(plot.margin = margin(7, 2, 2, 2))
# 
# fig <- fig + plot_layout(guides = 'collect')
# 
# fig <- fig + plot_annotation(tag_levels = 'a') & 
#   theme(plot.tag = element_text(size = 15), plot.tag.position = c(0.045, 1.07))
# 
# fig <- wrap_elements(panel = fig) +
#   labs(tag = "Mean Index") +
#   theme(
#     plot.tag = element_text(size = 20, angle = 90),
#     plot.tag.position = "left"
#   )
# 
# fig
# setwd("/Users/aleahw/Documents/Master's!!/Chapter_2/Figures")
# ggsave("Fig1facet.png", fig, units="in", width=10, height=6, dpi=600)


# #try all four stacked up
# fig <- together / Food / Biodiv / Climate & theme(plot.margin = margin(7, 2, 2, 2))
# 
# fig <- fig + plot_layout(guides = 'collect')
# 
# fig <- fig + plot_annotation(tag_levels = 'a') & 
#   theme(plot.tag = element_text(size = 15), plot.tag.position = c(0.045, 1.07))
# 
# fig <- wrap_elements(panel = fig) +
#   labs(tag = "Mean Index") +
#   theme(
#     plot.tag = element_text(size = 20, angle = 90),
#     plot.tag.position = "left"
#   )
# 
# fig

#try just three FCB stacked up
fig <- Food / Biodiv / Climate & theme(plot.margin = margin(7, 2, 2))

fig <- fig + plot_layout(guides = 'collect')

fig <- fig + plot_annotation(tag_levels = 'a') & 
  theme(plot.tag = element_text(size = 15), plot.tag.position = c(0.045, 1.07))

fig <- wrap_elements(panel = fig) +
  labs(tag = "Mean Index") +
  theme(
    plot.tag = element_text(size = 20, angle = 90),
    plot.tag.position = "left"
  )

fig

setwd("/Users/aleahw/Documents/Master's!!/Chapter_2/Figures")
# ggsave("Fig1facet.png", fig, units="in", width=10, height=10, dpi=600)


```

########### TASK 2 ########### 

##### Percent contribution to index: % contribution of taxonomic groups relative to F, C, B relative to the proportion of total production ###

```{r Loading in data}

Fbyfinfish <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Fweightedby_finfish.csv")
Fbyfinfish <- Fbyfinfish[, c(2:3)] #remove extra column
Fbyalgae <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Fweightedby_algae.csv")
Fbyalgae <- Fbyalgae[, c(2:3)] #remove extra column
Fbymolluscs <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Fweightedby_molluscs.csv")
Fbymolluscs <- Fbymolluscs[, c(2:3)] #remove extra column
Fbycrust <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Fweightedby_crustaceans.csv")
Fbycrust <- Fbycrust[, c(2:3)] #remove extra column

Cbyfinfish <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Cweightedby_finfish.csv")
Cbyfinfish <- Cbyfinfish[, c(2:3)] #remove extra column
Cbyalgae <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Cweightedby_algae.csv")
Cbyalgae <- Cbyalgae[, c(2:3)] #remove extra column
Cbymolluscs <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Cweightedby_molluscs.csv")
Cbymolluscs <- Cbymolluscs[, c(2:3)] #remove extra column
Cbycrust <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Cweightedby_crustaceans.csv")
Cbycrust <- Cbycrust[, c(2:3)] #remove extra column

Bbyfinfish <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Bweightedby_finfish.csv")
Bbyfinfish <- Bbyfinfish[, c(2:3)] #remove extra column
Bbyalgae <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Bweightedby_algae.csv")
Bbyalgae <- Bbyalgae[, c(2:3)] #remove extra column
Bbymolluscs <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Bweightedby_molluscs.csv")
Bbymolluscs <- Bbymolluscs[, c(2:3)] #remove extra column
Bbycrust <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Bweightedby_crustaceans.csv")
Bbycrust <- Bbycrust[, c(2:3)] #remove extra column

F_weighted_all <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Fweightedby_all.csv")
F_weighted_all <- F_weighted_all[, c(2:3)]
C_weighted_all <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Cweightedby_all.csv")
C_weighted_all <- C_weighted_all[, c(2:3)]
B_weighted_all <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/Bweightedby_all.csv")
B_weighted_all <- B_weighted_all[, c(2:3)]

weighting_totals <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/prodbytaxa_forweighting.csv") #annual production by taxonomic group
weighting_totals <- weighting_totals[, c(2:74)] #remove extra first column
weighting_totals <- weighting_totals[-c(3), ] #remove "inverts" category

#put Weighting_totals in reverse order
weighting_totals_rev <- rev(weighting_totals)
# weighting_totals_rev <- weighting_totals_rev[-c(3),] #remove inverts category!!!
```

```{r}
#First, calculate the % contribution of each taxa to annual production. We will eventually divide FCB indices by this proportion to find a ratio.

#divide taxa production in each year by the total prod in that year

new_frame <- weighting_totals #create new frame
new_frame <- new_frame[FALSE, ]

for (i in 2:nrow(weighting_totals)){ #for each taxonomic group
    for (b in 2:73){ #for each year
      total_prod <- weighting_totals[1, b] #get the total prod in that year
      index <- weighting_totals[i, b]/total_prod*100 #divide score by that species' total prod
      new_frame[i-1, b] <- index   #add these numbers to the frame
  } 
}

#rename
new_frame[1, 1] <-"Finfish"
new_frame[2, 1] <-"Algae"
new_frame[3, 1] <-"Crustacean"
new_frame[4, 1] <-"Mollusc"

#make long
new_frame <- pivot_longer(new_frame, cols = -c("category"),
                                names_to = "Year", values_to = "Perc_prod") #double check this
#fix years
year_labs <- rep(2021:1950, times=6) 

#rename year column in weighted_indexes
for (i in 1:nrow(new_frame)) {
  print(new_frame$Year[i])
  #replace each year with the actual year number from year_labs
  
  new_frame$Year[i] <- year_labs[i]
}

#save this
totalproduction <- new_frame
#goes one taxa at a time, from 2021 to 1950

#PUT IN year order
totalproduction <- totalproduction %>% arrange(Year)
```

```{r}

#merge
all_taxa <- merge(Fbyfinfish, Fbyalgae, by="Year")
all_taxa <- merge(all_taxa, Fbycrust, by="Year")
all_taxa <- merge(all_taxa, Fbymolluscs, by="Year")
all_taxa <- merge(all_taxa, F_weighted_all, by="Year")

#rename
colnames(all_taxa)[2] <- "Finfish"
colnames(all_taxa)[3] <- "Algae"
colnames(all_taxa)[4] <- "Crustaceans"
colnames(all_taxa)[5] <- "Molluscs"
colnames(all_taxa)[6] <- "All"

new_frame <- all_taxa[, -c(6)] #create new frame

for (i in 2:5) { #for each taxa
  # print(weighting_totals_rev$category[i])
 for (y in 1:72){ #for each year
   taxa_perc <- weighting_totals_rev[i, y]/weighting_totals_rev[1,y] #divide the taxa's production volume by the total volume of production in that year 
   # print(weighting_totals_rev[i, y])
   print(taxa_perc)
   product <- taxa_perc*all_taxa[y, i] #multiply taxa_perc by the index score of the taxa
   # print(all_taxa[y, i])
   # print(product)
   product <- product/all_taxa[y, 6] #divide the product by the FCB score that year when weighted by all taxa
   # print(product)

   new_frame[y, i] <- product*100 #put this number in a dataframe, convert from decimal to the numerical value of the percentage
   
 }
}

#make long
new_frame <- pivot_longer(new_frame, cols = -c("Year"),
                                names_to = "species", values_to = "index_perc") #check calculation

#save this
totalindex <- new_frame

#combine totalindex and totalprod
prod_index <- cbind(totalindex, totalproduction) #totalproduction created in chunk one of Step 12
prod_index <- prod_index[, -c(4, 5)]

#new column divides perc contribution to index, by perc contribution to production
prod_index[, 5] <- "new"
colnames(prod_index)[5] <- "ratio"

#calculate ratio for every row
for (i in 1:nrow(prod_index)) {
  ratio <- prod_index$index_perc[i]/prod_index$Perc_prod[i]
  prod_index$ratio[i] <- ratio
}

#graph this:
F_perc <-
  ggplot(prod_index, aes(x=Year, y=as.numeric(ratio) , color=species)) + geom_point()+
      geom_hline(yintercept = 1)+
      # labs(y = "Relative contribution to F")+
    labs(x = "R(F)", y = "")+
    theme_classic()+
    theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 15), axis.text.y = element_text(size = 15))+
      scale_color_manual(values = cbPalette, guide = "none")+
        geom_vline(xintercept = 1980, linetype = "dashed")+ #vertical lines
        geom_vline(xintercept = 2000, linetype = "dashed")+
        geom_vline(xintercept = 2021, linetype = "dashed")+
        scale_x_continuous(breaks = c(1963, 1990, 2010), labels = c("I", "II", "III"))
      # ylim(0, 1.5)

#SAVE
# ggsave("Ratio_F_prod.png", plot, height = 4, width = 8, dpi = 600) #make sure wd is set
```

```{r}
#merge
all_taxa <- merge(Cbyfinfish, Cbyalgae, by="Year")
all_taxa <- merge(all_taxa, Cbycrust, by="Year")
all_taxa <- merge(all_taxa, Cbymolluscs, by="Year")
all_taxa <- merge(all_taxa, C_weighted_all, by="Year")

#rename
colnames(all_taxa)[2] <- "Finfish"
colnames(all_taxa)[3] <- "Algae"
colnames(all_taxa)[4] <- "Crustaceans"
colnames(all_taxa)[5] <- "Molluscs"
colnames(all_taxa)[6] <- "All"

new_frame <- all_taxa[, -c(6)] #create new frame

for (i in 2:5) { #for each taxa
  # print(weighting_totals_rev$category[i])
 for (y in 1:72){ #for each year
   taxa_perc <- weighting_totals_rev[i, y]/weighting_totals_rev[1,y] #divide the taxa's production volume by the total volume of production in that year 
   # print(weighting_totals_rev[i, y])
   # print(taxa_perc)
   product <- taxa_perc*all_taxa[y, i] #multiply taxa_perc by the index score of the taxa
   # print(all_taxa[y, i])
   # print(product)
   product <- product/all_taxa[y, 6] #divide the product by the FCB score that year when weighted by all taxa
   # print(product)

   new_frame[y, i] <- product*100 #put this number in a dataframe, convert from decimal to the numerical value of the percentage
   
 }
}

#make long
new_frame <- pivot_longer(new_frame, cols = -c("Year"),
                                names_to = "species", values_to = "index_perc") #check calculation

#save this
totalindex <- new_frame

#combine totalindex and totalprod
prod_index <- cbind(totalindex, totalproduction) #totalproduction created in chunk one of Step 12
prod_index <- prod_index[, -c(4, 5)]

#new column divides perc contribution to index, by perc contribution to production
prod_index[, 5] <- "new"
colnames(prod_index)[5] <- "ratio"

#calculate ratio for every row
for (i in 1:nrow(prod_index)) {
  ratio <- prod_index$index_perc[i]/prod_index$Perc_prod[i]
  prod_index$ratio[i] <- ratio
}

#graph this:
C_perc <-
  ggplot(prod_index, aes(x=Year, y=as.numeric(ratio) , color=species)) + geom_point()+
      geom_hline(yintercept = 1)+
      # labs(y = "Relative contribution to C")+ #Contribution to C index:contribution to production
      scale_color_manual(values = cbPalette, guide = "none")+
      theme_classic()+
      theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 15), axis.text.y = element_text(size = 15))+
      labs(x = "R(C)", y = "")+
      scale_y_continuous(breaks = c(0.6, 0.8, 1.0, 1.2), limits = c(0.55, 1.25))+
        geom_vline(xintercept = 1980, linetype = "dashed")+ #vertical lines
        geom_vline(xintercept = 2000, linetype = "dashed")+
        geom_vline(xintercept = 2021, linetype = "dashed")+
        scale_x_continuous(breaks = c(1963, 1990, 2010), labels = c("I", "II", "III"))
      # ylim(0.5, 1.25)
```

```{r}
#merge
all_taxa <- merge(Bbyfinfish, Bbyalgae, by="Year")
all_taxa <- merge(all_taxa, Bbycrust, by="Year")
all_taxa <- merge(all_taxa, Bbymolluscs, by="Year")
all_taxa <- merge(all_taxa, B_weighted_all, by="Year")

#rename
colnames(all_taxa)[2] <- "Finfish"
colnames(all_taxa)[3] <- "Algae"
colnames(all_taxa)[4] <- "Crustaceans"
colnames(all_taxa)[5] <- "Molluscs"
colnames(all_taxa)[6] <- "All"

new_frame <- all_taxa[, -c(6)] #create new frame

for (i in 2:5) { #for each taxa
  # print(weighting_totals_rev$category[i])
 for (y in 1:72){ #for each year
   taxa_perc <- weighting_totals_rev[i, y]/weighting_totals_rev[1,y] #divide the taxa's production volume by the total volume of production in that year 
   # print(weighting_totals_rev[i, y])
   # print(taxa_perc)
   product <- taxa_perc*all_taxa[y, i] #multiply taxa_perc by the index score of the taxa
   # print(all_taxa[y, i])
   # print(product)
   product <- product/all_taxa[y, 6] #divide the product by the FCB score that year when weighted by all taxa
   # print(product)

   new_frame[y, i] <- product*100 #put this number in a dataframe, convert from decimal to the numerical value of the percentage
   
 }
}

#make long
new_frame <- pivot_longer(new_frame, cols = -c("Year"),
                                names_to = "species", values_to = "index_perc") #check calculation

#save this
totalindex <- new_frame

#combine totalindex and totalprod
prod_index <- cbind(totalindex, totalproduction) #totalproduction created in chunk one of Step 12
prod_index <- prod_index[, -c(4, 5)]

#new column divides perc contribution to index, by perc contribution to production
prod_index[, 5] <- "new"
colnames(prod_index)[5] <- "ratio"

#calculate ratio for every row
for (i in 1:nrow(prod_index)) {
  ratio <- prod_index$index_perc[i]/prod_index$Perc_prod[i]
  prod_index$ratio[i] <- ratio
}

#graph this:
B_perc <- ggplot(prod_index, aes(x=Year, y=as.numeric(ratio) , color=species)) + geom_point()+
      geom_hline(yintercept = 1)+
      # labs(y = "Relative contribution to B")+
      theme_classic()+
      theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 15), axis.text.y = element_text(size = 15))+
      labs(x = "R(B)", y = "")+
      scale_color_manual(values = cbPalette, guide = "none")+
      # ylim(0.5, 1.25)+
      scale_y_continuous(breaks = c(0.6, 0.8, 1.0, 1.2), limits = c(0.55, 1.25))+
        geom_vline(xintercept = 1980, linetype = "dashed")+ #vertical lines
        geom_vline(xintercept = 2000, linetype = "dashed")+
        geom_vline(xintercept = 2021, linetype = "dashed")+
        scale_x_continuous(breaks = c(1963, 1990, 2010), labels = c("I", "II", "III"))
```

#Percentage of total production
```{r}
#compared to a stacked % barchart of just production

weighting_totals <- read.csv("/Users/aleahw/Documents/Master's!!/Chapter_2/Data/prodbytaxa_forweighting.csv")

#remove extra columns
weighting_totals <- weighting_totals[, c(2:74)]

library(tidyr)
#make long
weighting_totals2 <- pivot_longer(weighting_totals, cols = -c(category),
                                names_to = "Year", values_to = "Score")

year_labs <- rep(2021:1950, times=6)

#rename year column in weighted_indexes
for (i in 1:nrow(weighting_totals2)) {
  print(weighting_totals2$Year[i])
  #replace each year with the actual year number from year_labs

  weighting_totals2$Year[i] <- year_labs[i]
}

weighting_totals2$Year <- as.numeric(weighting_totals2$Year) #make years numeric
weighting_totals2 <- weighting_totals2[order(weighting_totals2$Year),] #put earlier years first

#remove inverts
weighting_totals2 <- weighting_totals2[!(weighting_totals2$category == "inverts" | weighting_totals2$category ==  "all species"),]

# #delete "all" from weighting totals 2
# weighting_totals2  <- weighting_totals %>%
#   filter(species != "all species")

# #specify order of bars (from top to bottom)
weighting_totals2$species <- factor(weighting_totals2$category, levels=c('algae','crustacean', 'finfish','mollusc'))

perc_prod <-
  ggplot(weighting_totals2, aes(fill=category, y=Score, x=Year)) + 
    geom_bar(position="fill", stat="identity")+
    # labs(y = "Contribution to total production", fill = "Taxa")+
      labs(x = "", y = "", fill = "Taxa")+
      theme_classic()+
    theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 15), axis.text.y = element_text(size = 15), legend.title = element_text(size=15), legend.text = element_text(size = 15))+
    scale_fill_manual(values = cbPalette, labels = c("Algae", "Crustaceans", "Finfish", "Molluscs"))+
        geom_vline(xintercept = 1980, linetype = "dashed")+ #vertical lines
        geom_vline(xintercept = 2000, linetype = "dashed")+
        geom_vline(xintercept = 2021, linetype = "dashed")+
        scale_x_continuous(breaks = c(1963, 1990, 2010), labels = c("I", "II", "III"))
    # scale_y_continuous(breaks = c(0.00, 0.25, 0.5, 0.75, 1.00), labels = c("0", "25%", "50%", "75%","100%"))

# ggsave("percent_contribution_prod.png", plot, height = 4, width = 8, dpi = 600) #make sure wd is set
```

```{r}
fig2 <- (perc_prod|F_perc) / (B_perc|C_perc) & theme(plot.margin = margin(5, 1, 1, 1)) 
# & xlab(NULL) & ylab(NULL) 
#Fig a) Climate
#Fig b) Biodiv
#Fig c) Food

fig2 <- fig2 + plot_layout(guides = "collect")

fig2 <- fig2 + plot_annotation(tag_levels = 'a') & 
  theme(plot.tag = element_text(size = 15),
        plot.tag.position = c(0.04, 1.05))

fig2 <- wrap_elements(panel = fig2) +
  labs(tag = "Relative Contribution") +
  theme(
    plot.tag = element_text(size = 20, angle = 90),
    plot.tag.position = "left")

fig2

setwd("/Users/aleahw/Documents/Master's!!/Chapter_2/Figures")
ggsave("Fig2facet.png", fig2, , units="in", width=10, height=6, dpi=600)
```
